# Generated by Django 4.0.1 on 2022-01-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='disco',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='equipo',
            name='memoria',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='equipo',
            name='procesador',
            field=models.CharField(default='', max_length=100),
        ),
    ]
