# Generated by Django 4.0.1 on 2022-01-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_equipo_disco_equipo_memoria_equipo_procesador'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
