# Generated by Django 4.0.1 on 2022-01-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_empleado_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='serie',
            field=models.CharField(default='', max_length=100),
        ),
    ]
